config/routes.rb
Rails.application.routes.draw do
  get 'pages/homepage'

  get 'pages/about_us'

  get 'pages/index'

  get 'pages/about-us'

  get 'pages/contact'

  get 'pages/enquiry'

  root to: 'pages#homepage'

  devise_for :staff_accounts, class_name: "Employee::StaffAccount"

  namespace :employee do
    resources :staff_addresses
  end
  namespace :employee do
    resources :staff_details
  end
  namespace :employee do
    resources :roles
  end
  namespace :company do
    resources :advertisements
  end
  namespace :company do
    resources :branches
  end
  namespace :company do
    resources :headquarters
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
module Company
  def self.table_name_prefix
    'company_'
  end
end

app/models/company/advertisement.rb
class Company::Advertisement < ApplicationRecord
  belongs_to :company_branch, :class_name => 'Company::Branch'
end

app/models/company/branch.rb
class Company::Branch < ApplicationRecord
  belongs_to :company_headquarter, :class_name => 'Company::Headquarter'
  has_many :company_advertisements, :class_name => 'Company::Advertisement', foreign_key: 'company_branch_id'
end

app/models/company/headquarter.rb
class Company::Headquarter < ApplicationRecord
  has_many :company_branches, :class_name => 'Company::Branch', foreign_key: 'company_headquarter_id'

end

app/controllers/company/advertisements_controller.rb
class Company::AdvertisementsController < ApplicationController
  before_action :set_company_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /company/advertisements
  # GET /company/advertisements.json
  def index
    @company_advertisements = Company::Advertisement.all
  end

  # GET /company/advertisements/1
  # GET /company/advertisements/1.json
  def show
  end

  # GET /company/advertisements/new
  def new
    @company_advertisement = Company::Advertisement.new
  end

  # GET /company/advertisements/1/edit
  def edit
  end

  # POST /company/advertisements
  # POST /company/advertisements.json
  def create
    @company_advertisement = Company::Advertisement.new(company_advertisement_params)

    respond_to do |format|
      if @company_advertisement.save
        format.html { redirect_to @company_advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @company_advertisement }
      else
        format.html { render :new }
        format.json { render json: @company_advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/advertisements/1
  # PATCH/PUT /company/advertisements/1.json
  def update
    respond_to do |format|
      if @company_advertisement.update(company_advertisement_params)
        format.html { redirect_to @company_advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_advertisement }
      else
        format.html { render :edit }
        format.json { render json: @company_advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/advertisements/1
  # DELETE /company/advertisements/1.json
  def destroy
    @company_advertisement.destroy
    respond_to do |format|
      format.html { redirect_to company_advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_advertisement
      @company_advertisement = Company::Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_advertisement_params
      params.require(:company_advertisement).permit(:name, :description, :ads_image, :ads_duration, :ads_active, :company_branch_id)
    end
end

app/controllers/company/branches_controller.rb
class Company::BranchesController < ApplicationController
  before_action :set_company_branch, only: [:show, :edit, :update, :destroy]

  # GET /company/branches
  # GET /company/branches.json
  def index
    @company_branches = Company::Branch.all
  end

  # GET /company/branches/1
  # GET /company/branches/1.json
  def show
  end

  # GET /company/branches/new
  def new
    @company_branch = Company::Branch.new
  end

  # GET /company/branches/1/edit
  def edit
  end

  # POST /company/branches
  # POST /company/branches.json
  def create
    @company_branch = Company::Branch.new(company_branch_params)

    respond_to do |format|
      if @company_branch.save
        format.html { redirect_to @company_branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @company_branch }
      else
        format.html { render :new }
        format.json { render json: @company_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/branches/1
  # PATCH/PUT /company/branches/1.json
  def update
    respond_to do |format|
      if @company_branch.update(company_branch_params)
        format.html { redirect_to @company_branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_branch }
      else
        format.html { render :edit }
        format.json { render json: @company_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/branches/1
  # DELETE /company/branches/1.json
  def destroy
    @company_branch.destroy
    respond_to do |format|
      format.html { redirect_to company_branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_branch
      @company_branch = Company::Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_branch_params
      params.require(:company_branch).permit(:name, :street1, :street2, :postal_code, :city, :state, :country, :company_headquarter_id)
    end
end

app/controllers/company/headquarters_controller.rb
class Company::HeadquartersController < ApplicationController
  before_action :set_company_headquarter, only: [:show, :edit, :update, :destroy]

  # GET /company/headquarters
  # GET /company/headquarters.json
  def index
    @company_headquarters = Company::Headquarter.all
  end

  # GET /company/headquarters/1
  # GET /company/headquarters/1.json
  def show
  end

  # GET /company/headquarters/new
  def new
    @company_headquarter = Company::Headquarter.new
  end

  # GET /company/headquarters/1/edit
  def edit
  end

  # POST /company/headquarters
  # POST /company/headquarters.json
  def create
    @company_headquarter = Company::Headquarter.new(company_headquarter_params)

    respond_to do |format|
      if @company_headquarter.save
        format.html { redirect_to @company_headquarter, notice: 'Headquarter was successfully created.' }
        format.json { render :show, status: :created, location: @company_headquarter }
      else
        format.html { render :new }
        format.json { render json: @company_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/headquarters/1
  # PATCH/PUT /company/headquarters/1.json
  def update
    respond_to do |format|
      if @company_headquarter.update(company_headquarter_params)
        format.html { redirect_to @company_headquarter, notice: 'Headquarter was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_headquarter }
      else
        format.html { render :edit }
        format.json { render json: @company_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/headquarters/1
  # DELETE /company/headquarters/1.json
  def destroy
    @company_headquarter.destroy
    respond_to do |format|
      format.html { redirect_to company_headquarters_url, notice: 'Headquarter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_headquarter
      @company_headquarter = Company::Headquarter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_headquarter_params
      params.require(:company_headquarter).permit(:name, :registration_id)
    end
end

app/helpers/company/advertisements_helper.rb
module Company::AdvertisementsHelper
end

app/helpers/company/branches_helper.rb
module Company::BranchesHelper
end

app/helpers/company/headquarters_helper.rb
module Company::HeadquartersHelper
end

app/views/company/advertisements/_form.html.erb
<%= form_with(model: company_advertisement, local: true) do |form| %>
  <% if company_advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_advertisement.errors.count, "error") %> prohibited this company_advertisement from being saved:</h2>

      <ul>
      <% company_advertisement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_advertisement_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :company_advertisement_description %>
  </div>

  <div class="field">
    <%= form.label :ads_image %>
    <%= form.text_field :ads_image, id: :company_advertisement_ads_image %>
  </div>

  <div class="field">
    <%= form.label :ads_duration %>
    <%= form.number_field :ads_duration, id: :company_advertisement_ads_duration %>
  </div>

  <div class="field">
    <%= form.label :ads_active %>
    <%= form.check_box :ads_active, id: :company_advertisement_ads_active %>
  </div>

  <div class="field">
    <%= form.label :company_branch_id %>
    <%= form.text_field :company_branch_id, id: :company_advertisement_company_branch_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/company/advertisements/edit.html.erb
<h1>Editing Company Advertisement</h1>

<%= render 'form', company_advertisement: @company_advertisement %>

<%= link_to 'Show', @company_advertisement %> |
<%= link_to 'Back', company_advertisements_path %>

app/views/company/advertisements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Ads image</th>
      <th>Ads duration</th>
      <th>Ads active</th>
      <th>Company branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_advertisements.each do |company_advertisement| %>
      <tr>
        <td><%= company_advertisement.name %></td>
        <td><%= company_advertisement.description %></td>
        <td><%= company_advertisement.ads_image %></td>
        <td><%= company_advertisement.ads_duration %></td>
        <td><%= company_advertisement.ads_active %></td>
        <td><%= company_advertisement.company_branch %></td>
        <td><%= link_to 'Show', company_advertisement %></td>
        <td><%= link_to 'Edit', edit_company_advertisement_path(company_advertisement) %></td>
        <td><%= link_to 'Destroy', company_advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Advertisement', new_company_advertisement_path %>

app/views/company/advertisements/new.html.erb
<h1>New Company Advertisement</h1>

<%= render 'form', company_advertisement: @company_advertisement %>

<%= link_to 'Back', company_advertisements_path %>

app/views/company/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_advertisement.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company_advertisement.description %>
</p>

<p>
  <strong>Ads image:</strong>
  <%= @company_advertisement.ads_image %>
</p>

<p>
  <strong>Ads duration:</strong>
  <%= @company_advertisement.ads_duration %>
</p>

<p>
  <strong>Ads active:</strong>
  <%= @company_advertisement.ads_active %>
</p>

<p>
  <strong>Company branch:</strong>
  <%= @company_advertisement.company_branch %>
</p>

<%= link_to 'Edit', edit_company_advertisement_path(@company_advertisement) %> |
<%= link_to 'Back', company_advertisements_path %>