config/routes.rb
Rails.application.routes.draw do
  get 'pages/homepage'

  get 'pages/about_us'

  get 'pages/index'

  get 'pages/about-us'

  get 'pages/contact'

  get 'pages/enquiry'

  root to: 'pages#homepage'

  devise_for :staff_accounts, class_name: "Employee::StaffAccount"

  namespace :employee do
    resources :staff_addresses
  end
  namespace :employee do
    resources :staff_details
  end
  namespace :employee do
    resources :roles
  end
  namespace :company do
    resources :advertisements
  end
  namespace :company do
    resources :branches
  end
  namespace :company do
    resources :headquarters
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
module Company
  def self.table_name_prefix
    'company_'
  end
end

app/models/company/advertisement.rb
class Company::Advertisement < ApplicationRecord
  belongs_to :company_branch, :class_name => 'Company::Branch'
end

app/models/company/branch.rb
class Company::Branch < ApplicationRecord
  belongs_to :company_headquarter, :class_name => 'Company::Headquarter'
  has_many :company_advertisements, :class_name => 'Company::Advertisement', foreign_key: 'company_branch_id'
end

app/models/company/headquarter.rb
class Company::Headquarter < ApplicationRecord
  has_many :company_branches, :class_name => 'Company::Branch', foreign_key: 'company_headquarter_id'

end

app/controllers/company/advertisements_controller.rb
class Company::AdvertisementsController < ApplicationController
  before_action :set_company_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /company/advertisements
  # GET /company/advertisements.json
  def index
    @company_advertisements = Company::Advertisement.all
  end

  # GET /company/advertisements/1
  # GET /company/advertisements/1.json
  def show
  end

  # GET /company/advertisements/new
  def new
    @company_advertisement = Company::Advertisement.new
  end

  # GET /company/advertisements/1/edit
  def edit
  end

  # POST /company/advertisements
  # POST /company/advertisements.json
  def create
    @company_advertisement = Company::Advertisement.new(company_advertisement_params)

    respond_to do |format|
      if @company_advertisement.save
        format.html { redirect_to @company_advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @company_advertisement }
      else
        format.html { render :new }
        format.json { render json: @company_advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/advertisements/1
  # PATCH/PUT /company/advertisements/1.json
  def update
    respond_to do |format|
      if @company_advertisement.update(company_advertisement_params)
        format.html { redirect_to @company_advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_advertisement }
      else
        format.html { render :edit }
        format.json { render json: @company_advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/advertisements/1
  # DELETE /company/advertisements/1.json
  def destroy
    @company_advertisement.destroy
    respond_to do |format|
      format.html { redirect_to company_advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_advertisement
      @company_advertisement = Company::Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_advertisement_params
      params.require(:company_advertisement).permit(:name, :description, :ads_image, :ads_duration, :ads_active, :company_branch_id)
    end
end

app/controllers/company/branches_controller.rb
class Company::BranchesController < ApplicationController
  before_action :set_company_branch, only: [:show, :edit, :update, :destroy]

  # GET /company/branches
  # GET /company/branches.json
  def index
    @company_branches = Company::Branch.all
  end

  # GET /company/branches/1
  # GET /company/branches/1.json
  def show
  end

  # GET /company/branches/new
  def new
    @company_branch = Company::Branch.new
  end

  # GET /company/branches/1/edit
  def edit
  end

  # POST /company/branches
  # POST /company/branches.json
  def create
    @company_branch = Company::Branch.new(company_branch_params)

    respond_to do |format|
      if @company_branch.save
        format.html { redirect_to @company_branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @company_branch }
      else
        format.html { render :new }
        format.json { render json: @company_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/branches/1
  # PATCH/PUT /company/branches/1.json
  def update
    respond_to do |format|
      if @company_branch.update(company_branch_params)
        format.html { redirect_to @company_branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_branch }
      else
        format.html { render :edit }
        format.json { render json: @company_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/branches/1
  # DELETE /company/branches/1.json
  def destroy
    @company_branch.destroy
    respond_to do |format|
      format.html { redirect_to company_branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_branch
      @company_branch = Company::Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_branch_params
      params.require(:company_branch).permit(:name, :street1, :street2, :postal_code, :city, :state, :country, :company_headquarter_id)
    end
end

app/controllers/company/headquarters_controller.rb
class Company::HeadquartersController < ApplicationController
  before_action :set_company_headquarter, only: [:show, :edit, :update, :destroy]

  # GET /company/headquarters
  # GET /company/headquarters.json
  def index
    @company_headquarters = Company::Headquarter.all
  end

  # GET /company/headquarters/1
  # GET /company/headquarters/1.json
  def show
  end

  # GET /company/headquarters/new
  def new
    @company_headquarter = Company::Headquarter.new
  end

  # GET /company/headquarters/1/edit
  def edit
  end

  # POST /company/headquarters
  # POST /company/headquarters.json
  def create
    @company_headquarter = Company::Headquarter.new(company_headquarter_params)

    respond_to do |format|
      if @company_headquarter.save
        format.html { redirect_to @company_headquarter, notice: 'Headquarter was successfully created.' }
        format.json { render :show, status: :created, location: @company_headquarter }
      else
        format.html { render :new }
        format.json { render json: @company_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/headquarters/1
  # PATCH/PUT /company/headquarters/1.json
  def update
    respond_to do |format|
      if @company_headquarter.update(company_headquarter_params)
        format.html { redirect_to @company_headquarter, notice: 'Headquarter was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_headquarter }
      else
        format.html { render :edit }
        format.json { render json: @company_headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/headquarters/1
  # DELETE /company/headquarters/1.json
  def destroy
    @company_headquarter.destroy
    respond_to do |format|
      format.html { redirect_to company_headquarters_url, notice: 'Headquarter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_headquarter
      @company_headquarter = Company::Headquarter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_headquarter_params
      params.require(:company_headquarter).permit(:name, :registration_id)
    end
end

app/helpers/company/advertisements_helper.rb
module Company::AdvertisementsHelper
end

app/helpers/company/branches_helper.rb
module Company::BranchesHelper
end

app/helpers/company/headquarters_helper.rb
module Company::HeadquartersHelper
end

app/views/company/headquarters/_form.html.erb
<%= form_with(model: company_headquarter, local: true) do |form| %>
  <% if company_headquarter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_headquarter.errors.count, "error") %> prohibited this company_headquarter from being saved:</h2>

      <ul>
      <% company_headquarter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_headquarter_name %>
  </div>

  <div class="field">
    <%= form.label :registration_id %>
    <%= form.text_field :registration_id, id: :company_headquarter_registration_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/company/headquarters/edit.html.erb
<h1>Editing Company Headquarter</h1>

<%= render 'form', company_headquarter: @company_headquarter %>

<%= link_to 'Show', @company_headquarter %> |
<%= link_to 'Back', company_headquarters_path %>

app/views/company/headquarters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Headquarters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_headquarters.each do |company_headquarter| %>
      <tr>
        <td><%= company_headquarter.name %></td>
        <td><%= company_headquarter.registration_id %></td>
        <td><%= link_to 'Show', company_headquarter %></td>
        <td><%= link_to 'Edit', edit_company_headquarter_path(company_headquarter) %></td>
        <td><%= link_to 'Destroy', company_headquarter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Headquarter', new_company_headquarter_path %>

app/views/company/headquarters/new.html.erb
<h1>New Company Headquarter</h1>

<%= render 'form', company_headquarter: @company_headquarter %>

<%= link_to 'Back', company_headquarters_path %>

app/views/company/headquarters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_headquarter.name %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @company_headquarter.registration_id %>
</p>

<%= link_to 'Edit', edit_company_headquarter_path(@company_headquarter) %> |
<%= link_to 'Back', company_headquarters_path %>