config/routes.rb
Rails.application.routes.draw do
  get 'pages/homepage'

  get 'pages/about_us'

  get 'pages/index'

  get 'pages/about-us'

  get 'pages/contact'

  get 'pages/enquiry'

  root to: 'pages#homepage'

  devise_for :staff_accounts, class_name: "Employee::StaffAccount"

  namespace :employee do
    resources :staff_addresses
  end
  namespace :employee do
    resources :staff_details
  end
  namespace :employee do
    resources :roles
  end
  namespace :company do
    resources :advertisements
  end
  namespace :company do
    resources :branches
  end
  namespace :company do
    resources :headquarters
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
module Employee
  def self.table_name_prefix
    'employee_'
  end
end

app/models/employee/role.rb
class Employee::Role < ApplicationRecord
end

app/models/employee/staff_account.rb
class Employee::StaffAccount < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :employee_staff_detail, :class_name => 'Employee::StaffDetail'
end

app/models/employee/staff_address.rb
class Employee::StaffAddress < ApplicationRecord
  belongs_to :employee_staff_detail, :class_name => 'Employee::StaffDetail'
end

app/models/employee/staff_detail.rb
class Employee::StaffDetail < ApplicationRecord
  has_many :employee_staff_addresses, :class_name => 'Employee::StaffAddress', foreign_key: 'employee_staff_detail_id'
  has_one :employee_staff_account, :class_name => 'Employee::StaffAccount', foreign_key: 'employee_staff_detail_id'
end

app/controllers/employee/roles_controller.rb
class Employee::RolesController < ApplicationController
  before_action :set_employee_role, only: [:show, :edit, :update, :destroy]

  # GET /employee/roles
  # GET /employee/roles.json
  def index
    @employee_roles = Employee::Role.all
  end

  # GET /employee/roles/1
  # GET /employee/roles/1.json
  def show
  end

  # GET /employee/roles/new
  def new
    @employee_role = Employee::Role.new
  end

  # GET /employee/roles/1/edit
  def edit
  end

  # POST /employee/roles
  # POST /employee/roles.json
  def create
    @employee_role = Employee::Role.new(employee_role_params)

    respond_to do |format|
      if @employee_role.save
        format.html { redirect_to @employee_role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @employee_role }
      else
        format.html { render :new }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee/roles/1
  # PATCH/PUT /employee/roles/1.json
  def update
    respond_to do |format|
      if @employee_role.update(employee_role_params)
        format.html { redirect_to @employee_role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_role }
      else
        format.html { render :edit }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee/roles/1
  # DELETE /employee/roles/1.json
  def destroy
    @employee_role.destroy
    respond_to do |format|
      format.html { redirect_to employee_roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_role
      @employee_role = Employee::Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_role_params
      params.require(:employee_role).permit(:name)
    end
end

app/controllers/employee/staff_addresses_controller.rb
class Employee::StaffAddressesController < ApplicationController
  before_action :set_employee_staff_address, only: [:show, :edit, :update, :destroy]

  # GET /employee/staff_addresses
  # GET /employee/staff_addresses.json
  def index
    @employee_staff_addresses = Employee::StaffAddress.all
  end

  # GET /employee/staff_addresses/1
  # GET /employee/staff_addresses/1.json
  def show
  end

  # GET /employee/staff_addresses/new
  def new
    @employee_staff_address = Employee::StaffAddress.new
  end

  # GET /employee/staff_addresses/1/edit
  def edit
  end

  # POST /employee/staff_addresses
  # POST /employee/staff_addresses.json
  def create
    @employee_staff_address = Employee::StaffAddress.new(employee_staff_address_params)

    respond_to do |format|
      if @employee_staff_address.save
        format.html { redirect_to @employee_staff_address, notice: 'Staff address was successfully created.' }
        format.json { render :show, status: :created, location: @employee_staff_address }
      else
        format.html { render :new }
        format.json { render json: @employee_staff_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee/staff_addresses/1
  # PATCH/PUT /employee/staff_addresses/1.json
  def update
    respond_to do |format|
      if @employee_staff_address.update(employee_staff_address_params)
        format.html { redirect_to @employee_staff_address, notice: 'Staff address was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_staff_address }
      else
        format.html { render :edit }
        format.json { render json: @employee_staff_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee/staff_addresses/1
  # DELETE /employee/staff_addresses/1.json
  def destroy
    @employee_staff_address.destroy
    respond_to do |format|
      format.html { redirect_to employee_staff_addresses_url, notice: 'Staff address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_staff_address
      @employee_staff_address = Employee::StaffAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_staff_address_params
      params.require(:employee_staff_address).permit(:employee_staff_detail_id, :street1, :street2, :postal, :city, :state, :country)
    end
end

app/controllers/employee/staff_details_controller.rb
class Employee::StaffDetailsController < ApplicationController
  before_action :set_employee_staff_detail, only: [:show, :edit, :update, :destroy]

  # GET /employee/staff_details
  # GET /employee/staff_details.json
  def index
    @employee_staff_details = Employee::StaffDetail.all
  end

  # GET /employee/staff_details/1
  # GET /employee/staff_details/1.json
  def show
  end

  # GET /employee/staff_details/new
  def new
    @employee_staff_detail = Employee::StaffDetail.new
  end

  # GET /employee/staff_details/1/edit
  def edit
  end

  # POST /employee/staff_details
  # POST /employee/staff_details.json
  def create
    @employee_staff_detail = Employee::StaffDetail.new(employee_staff_detail_params)

    respond_to do |format|
      if @employee_staff_detail.save
        format.html { redirect_to @employee_staff_detail, notice: 'Staff detail was successfully created.' }
        format.json { render :show, status: :created, location: @employee_staff_detail }
      else
        format.html { render :new }
        format.json { render json: @employee_staff_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee/staff_details/1
  # PATCH/PUT /employee/staff_details/1.json
  def update
    respond_to do |format|
      if @employee_staff_detail.update(employee_staff_detail_params)
        format.html { redirect_to @employee_staff_detail, notice: 'Staff detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_staff_detail }
      else
        format.html { render :edit }
        format.json { render json: @employee_staff_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee/staff_details/1
  # DELETE /employee/staff_details/1.json
  def destroy
    @employee_staff_detail.destroy
    respond_to do |format|
      format.html { redirect_to employee_staff_details_url, notice: 'Staff detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_staff_detail
      @employee_staff_detail = Employee::StaffDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_staff_detail_params
      params.require(:employee_staff_detail).permit(:first_name, :last_name, :gender, :nric, :dob, :socso_id, :phone_number, :spouse_name, :spouse_phone_number)
    end
end

app/helpers/employee/roles_helper.rb
module Employee::RolesHelper
end

app/helpers/employee/staff_addresses_helper.rb
module Employee::StaffAddressesHelper
end

app/helpers/employee/staff_details_helper.rb
module Employee::StaffDetailsHelper
end

app/views/employee/staff_addresses/_form.html.erb
<%= form_with(model: employee_staff_address, local: true) do |form| %>
  <% if employee_staff_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_staff_address.errors.count, "error") %> prohibited this employee_staff_address from being saved:</h2>

      <ul>
      <% employee_staff_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_staff_detail_id %>
    <%= form.text_field :employee_staff_detail_id, id: :employee_staff_address_employee_staff_detail_id %>
  </div>

  <div class="field">
    <%= form.label :street1 %>
    <%= form.text_field :street1, id: :employee_staff_address_street1 %>
  </div>

  <div class="field">
    <%= form.label :street2 %>
    <%= form.text_field :street2, id: :employee_staff_address_street2 %>
  </div>

  <div class="field">
    <%= form.label :postal %>
    <%= form.text_field :postal, id: :employee_staff_address_postal %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :employee_staff_address_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :employee_staff_address_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :employee_staff_address_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee/staff_addresses/edit.html.erb
<h1>Editing Employee Staff Address</h1>

<%= render 'form', employee_staff_address: @employee_staff_address %>

<%= link_to 'Show', @employee_staff_address %> |
<%= link_to 'Back', employee_staff_addresses_path %>

app/views/employee/staff_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Staff Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Employee staff detail</th>
      <th>Street1</th>
      <th>Street2</th>
      <th>Postal</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_staff_addresses.each do |employee_staff_address| %>
      <tr>
        <td><%= employee_staff_address.employee_staff_detail.first_name %></td>
        <td><%= employee_staff_address.street1 %></td>
        <td><%= employee_staff_address.street2 %></td>
        <td><%= employee_staff_address.postal %></td>
        <td><%= employee_staff_address.city %></td>
        <td><%= employee_staff_address.state %></td>
        <td><%= employee_staff_address.country %></td>
        <td><%= link_to 'Show', employee_staff_address %></td>
        <td><%= link_to 'Edit', edit_employee_staff_address_path(employee_staff_address) %></td>
        <td><%= link_to 'Destroy', employee_staff_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Staff Address', new_employee_staff_address_path %>

app/views/employee/staff_addresses/new.html.erb
<h1>New Employee Staff Address</h1>

<%= render 'form', employee_staff_address: @employee_staff_address %>

<%= link_to 'Back', employee_staff_addresses_path %>

app/views/employee/staff_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee staff detail:</strong>
  <%= @employee_staff_address.employee_staff_detail %>
</p>

<p>
  <strong>Street1:</strong>
  <%= @employee_staff_address.street1 %>
</p>

<p>
  <strong>Street2:</strong>
  <%= @employee_staff_address.street2 %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @employee_staff_address.postal %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee_staff_address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee_staff_address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee_staff_address.country %>
</p>

<%= link_to 'Edit', edit_employee_staff_address_path(@employee_staff_address) %> |
<%= link_to 'Back', employee_staff_addresses_path %>